### ISSUE TITLE
Badge is not updated after updating the Docker image

### ISSUE THREAD

**Issue by FooBarWidget** [CenturyLinkLabs/imagelayers-graph#77]
I just pushed out a new release of phusion/baseimage. The 'latest' tag has been updated. However, https://badge.imagelayers.io/phusion/baseimage:latest.svg is still showing the old size (280 MB) instead of the new size (238 MB).

**Comment by bdehamer** [comment]
@FooBarWidget Depending on the number of layers in the image it can be very expensive to collect the size information for an image (we have to make a number of API calls against the Docker Hub to collect all the necessary info). In order to avoid slamming the Docker Hub constantly, we are caching badges that are generated for six hours before we regenerate them.

Please check your badge again after the six hour cache expiration and see if it has updated properly.

**Comment by FooBarWidget** [comment]
Ok, sounds reasonable.

**Comment by bdehamer** [comment]
@FooBarWidget looks like your badge has been updated. Gonna close this issue. Thanks.

**Comment by FooBarWidget** [comment]
I have a suggestion. Even though the image is cached for 6 hours, if I go to https://imagelayers.io/?images=phusion%2Fbaseimage:latest, the latest state of the image is shown. Looks like there is no caching going on there. Can't you make that endpoint check whether the image is up-to-date, and if not, refresh it from there?

**Comment by bdehamer** [comment]
Good idea. I'll add that as an enhancement idea.
