### ISSUE TITLE
I don't understand why my image won't load on your site.

### ISSUE THREAD

**Issue by blacktop** [CenturyLinkLabs/imagelayers-graph#83]
https://imagelayers.io/?images=malice%2Ffileinfo:latest

**Comment by manuwell** [comment]
there is something wrong with their imagelayers API services. 

the analyze URL https://imagelayers.io:8888/registry/analyze isn't responding. This project seems to be abandoned =(. 

Hope someone appears to save this awesome project.

**Comment by ckleban** [comment]
@blacktop, this seems to load fine now. @manuwell, we did have to step away from it for a bit, but are working to get back into it.

**Comment by manuwell** [comment]
@ckleban, happy to hear that. 
this service looks very nice :v:

**Comment by davidgardner11** [comment]
@blacktop and @manuwell -- closing this ticket out. Please post again if you experience any issues.

**Comment by blacktop** [comment]
I am getting 0 for all the layers on this build: https://imagelayers.io/?images=blacktop%2Felk:latest

**Comment by ckleban** [comment]
@blacktop Thanks for the info. This issue is being tracked in issue https://github.com/CenturyLinkLabs/imagelayers-graph/issues/85. We plan to take a look at it starting next week.

**Comment by manuwell** [comment]
Seems [https://imagelayers.io:8888/registry/analyze](https://imagelayers.io:8888/registry/analyze) isn't working again. =(

**Comment by ckleban** [comment]
@manuwell Thanks. We will take a look. Out of curiosity, what are you doing to trigger/call that url? 

thanks
chris

**Comment by manuwell** [comment]
Nothing, I like to see containers layers and ImageLayers provides a cool interface for it. 
When it crashes I look at Chrome Console to see what is happening and almost often is this endpoint.

**Comment by ntfrnzn** [comment]
The problem seems to be intermittent.  Currently, fro example, the library php:latest image is failing to display at https://imagelayers.io.   Some detailed inspection shows that the problem occurs when trying to load metadata for only one of the sublayers of the php image.  The error returned from the v1 registry api is 404 - {"error": "Image is being uploaded, retry later"}.   However, the full php image downloads fine, so this looks like a problem in the docker registry api.

What we should do is (1) skip over that layer and display the rest and/or (2) migrate to using the v2 api.  I suspect that the docker registry v1 interface will not be aggressively maintained.

**Comment by blacktop** [comment]
I am getting layer counts but not image size values now.

https://imagelayers.io/?images=blacktop%2Felk:latest
